name: opus
description: Manage your clients and invoices easily.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  email_validator: ^1.0.0
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: productsans
      fonts:
        - asset: assets/fonts/productsans.ttf
        - asset: assets/fonts/productsans_bold.ttf
          weight: 800
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
        - asset: assets/fonts/roboto_bold.ttf
          weight: 800